import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import { NavigationItem, Scaffold } from "@noba/web-layout";
import "../globals.css";
import {
	CalendarIcon,
	ChartPieIcon,
	DocumentDuplicateIcon,
	FolderIcon,
	HomeIcon,
	UsersIcon,
} from "@heroicons/react/24/outline";

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

const navigation: NavigationItem[] = [
	{ name: "Dashboard", href: "/", icon: <HomeIcon /> },
	{ name: "Users", href: "/users", icon: <UsersIcon /> },
	{ name: "Projects", href: "#", icon: <FolderIcon /> },
	{ name: "Calendar", href: "#", icon: <CalendarIcon /> },
	{ name: "Documents", href: "#", icon: <DocumentDuplicateIcon /> },
	{ name: "Reports", href: "#", icon: <ChartPieIcon /> },
];

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html lang="en" className="h-full bg-white">
			<body className={`${GeistSans.className} h-full`}>
				<Scaffold navigationItems={navigation}>{children}</Scaffold>
			</body>
		</html>
	);
}
