import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import { NavigationItem, Scaffold } from "@noba/web-layout";
import "./globals.css";
import {
	CalendarIcon,
	ChartPieIcon,
	DocumentDuplicateIcon,
	FolderIcon,
	HomeIcon,
	UsersIcon,
} from "@heroicons/react/24/outline";

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

const navigation: NavigationItem[] = [
	{ name: "Dashboard", href: "/", icon: <HomeIcon />, current: true },
	{ name: "Users", href: "/users", icon: <UsersIcon />, current: false },
	{ name: "Projects", href: "#", icon: <FolderIcon />, current: false },
	{ name: "Calendar", href: "#", icon: <CalendarIcon />, current: false },
	{ name: "Documents", href: "#", icon: <DocumentDuplicateIcon />, current: false },
	{ name: "Reports", href: "#", icon: <ChartPieIcon />, current: false },
];

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html lang="en" className="h-full bg-white">
			<body className={`${GeistSans.className} h-full`}>
				<Scaffold navigationItems={navigation}>{children}</Scaffold>
			</body>
		</html>
	);
}
